### PR TITLE
Add sort feature

### LINKED ISSUE #62: Sort feature
As a user, I can sort the list of clients by their attributes, so that the list is more organized.

### PR DESCRIPTION
**Pull request by Ashuh**
Allows the client list to be sorted according to one or more of their attributes.

Comand format: `sort [FIELD]...`

Allowed values for `FIELD`: 
- `name`
- `phone`
- `email`
- `favourite`
- `address`
- `usertype`
- `num_property`

Sorting order can be reversed by prefixing a `FIELD` with `!`

Example usage: `sort name phone email !address`

To do:
- [x] Implementation
- [x] Testing
- [x] Documentation

Closes #62

### CODE REVIEW

**Review by waffledood — APPROVED** [review]
LGTM! 👍 

seems like there are some failing tests on the macos build CI script?

**Comment by Ashuh** [comment]
That would be due to the issue described in #103

**Review by cindyangXQ — COMMENTED** [review]
Could delete the failing tests then.

**Comment by Ashuh** [comment]
We can merge this once #106 is merged

**Review by hsiaojietng — APPROVED** [review]
LGTM

**Pull request merged**
