### PR TITLE
Fix issue with closing Main window

### LINKED ISSUE #105: Problem with statistics window affecting main window
There is a currently a issue exiting the main window if the `stats` command is not called a single time before exiting.
This is because `statisticsWindow = new StatisticsWindow(logic);` is only called if the stats command has been called before so `statisticsWindow.hide();` will throw a error since `statisticsWindow` is `null`.

### PR DESCRIPTION
**Pull request by howardwhw2**
There is a currently a issue exiting the main window if the `stats` command is not called a single time before exiting.
This is because `statisticsWindow = new StatisticsWindow(logic);` is only called if the `stats` command has been called before so `        statisticsWindow.hide();` will throw a error since `statisticsWindow` is `null`.

Changed behaviour to create a new `statisticsWindow` on `mainwindow` initalization and refreshes `statisticsWindow` on command call instead.

Minor issue:
pie chart colour will change each time the stats command is called.

closes #105

### CODE REVIEW

**Comment by hsiaojietng** [comment]
For me this doesn't work, I have to populate the data first before creating the instance of Statistics Window. I will work sometthing out and will let you know, so just keep this PR.
image

**Review by cindyangXQ — APPROVED** [review]
LGTM

**Comment by hsiaojietng** [comment]
@howardwhw2 Can you change the StatisticsWindow.fxml to
``` Java
<?xml version="1.0" encoding="UTF-8"?>

<?import javafx.scene.*?>

<?import javafx.stage.Stage?>
<?import javafx.scene.image.Image?>
<?import java.net.URL?>
<?import javafx.scene.chart.PieChart?>
<Stage minHeight="600" minWidth="450" title="Statistics window" xmlns="http://javafx.com/javafx/11" xmlns:fx="http://javafx.com/fxml/1">
    <icons>
        <Image url="@/images/address_book_32.png" />
    </icons>
    <scene>
        <Scene>
            <stylesheets>
                <URL value="@DarkTheme.css" />
                <URL value="@Extensions.css" />
            </stylesheets>
            <PieChart prefHeight="380.0" prefWidth="320.0" title="Popular areas for buyers and sellers" fx:id="pieChart"/>
        </Scene>
    </scene>
</Stage>
```
Before this change, I was facing an issue where the labels of the pie charts go haywire when you close the Statisticwindow and then open it the second time (using command or menu item).

**Comment by howardwhw2** [comment]
@hsiaojietng `statisticswindow.fxml` has been updated as well. Will proceed to merge after your approval.

**Review by hsiaojietng — APPROVED** [review]
LGTM

**Pull request merged**
